version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/guitarrapc/git-shallow-clone
  git-shallow-clone: guitarrapc/git-shallow-clone@2.8.0

jobs:
  build:
    docker:
      - image: cimg/base:2023.10
    steps:
      - git-shallow-clone/checkout
      - run: echo "this is the build job"
      - run: cat README.md
  test:
    docker:
      - image: cimg/base:2023.10
    steps:
      - git-shallow-clone/checkout
      - run: echo "this is the test job"
      - run: cat README.md

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
