version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.10
    steps:
      # - checkout の代わりに自分で git clone する
      - run: git clone --depth 1 --no-single-branch "$CIRCLE_REPOSITORY_URL"
      - run: echo "this is the build job"
      - run: cat README.md
  test:
    docker:
      - image: cimg/base:2023.10
    steps:
      # - checkout の代わりに自分で git clone する
      - run: git clone --depth 1 --no-single-branch "$CIRCLE_REPOSITORY_URL"
      - run: echo "this is the test job"
      - run: cat README.md

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
